#!/bin/bash

BUILDER="/cygdrive/c/Program Files (x86)/MSBuild/14.0/Bin/MSBuild.exe"

echo "Mapping drive"
net use \\\\CI\\ci /user:ci "LxVV5JpIGAmlKTgJOTpX56D53WO391lT"

cd //CI/ci/sources/libtranslate
if [[ $? -ne 0 ]]; then
echo Cannot cd into build
exit 1
fi

cd codegen/native/
git submodule init
git submodule update
if [[ $? -ne 0 ]]; then
    echo "Failed to check native submodule"
    exit 1
fi
cd ../../

STATUS=0
export PATH=/opt/php/:$PATH

echo "{CI_SECTION_START} mkcstables.php"
php codegen/s2trad.php
if [[ $? -ne 0 ]]; then
    STATUS=1
fi
php codegen/synpatch/mkcstable.php
if [[ $? -ne 0 ]]; then
    STATUS=1
fi
php codegen/vtrans/mkcstable.php
if [[ $? -ne 0 ]]; then
    STATUS=1
fi
echo "{CI_SECTION_END}"

echo "{CI_SECTION_START} MSBuild"
"$BUILDER" libtranslate.vcxproj /p:Configuration="Release"
if [[ $? -ne 0 ]]; then
    STATUS=1
fi
echo "{CI_SECTION_END}"

echo "{CI_SECTION_START} Test"
echo "No tests yet."
echo "{CI_SECTION_END}"

if [[ $STATUS -ne 0 ]]; then
    exit 1
fi
